[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "tesseract", "libtesseract-dev"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "echo 'Build completed'"
]

[start]
cmd = "python3 app.py"
